kaminari を使ってページング処理を実装する
kohei-miyazawa/fjord-books_app pull request #1
Opened 2020-11-26 01:37 UTC by kohei-miyazawa

## プラクティス概要
Rails アプリに kaminariを使ったページングを実装する。

### 注意点
ページングを付ける場合は、必ず「並び順が一意になるorder」も指定するようにしよう。

## 実装概要
- `kaminari`のインストール
-  `index`ページに各ページへのリンクと案内を表示
-  `@books = Book.order(created_at: :desc).order(:id).page(params[:page])`で並びが一意になるよう修正

### 画面のスクショ
<img width="448" alt="スクリーンショット 2020-11-26 10 18 04" src="https://user-images.githubusercontent.com/50073648/100298028-62f8a780-2fd3-11eb-9266-e2c4f4be5c70.png">

2020-11-30 02:20 UTC, komagata requested changes

2020-11-30 02:20 UTC, komagata commented on app/controllers/books_controller.rb
> +    @books = Book.order(created_at: :desc).order(:id).page(params[:page])
結果はOKあってるのですが、下記の方がわかりやすいかもです。

```suggestion
    @books = Book.order(created_at: :desc, id: :asc).page(params[:page])
```

2020-11-30 02:20 UTC, komagata commented on app/views/books/index.html.erb
> +  <%= page_entries_info @books %>
`page_entries_info`などは、pagerのテンプレートを編集することで、それらを含めて`paginate @books`だけで全て表示されるのでそちらを使うのが良いと思います〜

2021-01-08 05:56 UTC, kohei-miyazawa commented on app/controllers/books_controller.rb
> +    @books = Book.order(created_at: :desc).order(:id).page(params[:page])
並びを一意にするためのidの指定の仕方がわからず、勉強になりました。
ご指摘ありがとうございます。

2021-01-08 06:30 UTC, kohei-miyazawa commented on app/views/books/index.html.erb
> +  <%= page_entries_info @books %>
ご指摘ありがとうございます。
`_paginator.html.erb`に`page_entries_info`を含めることで、`paginate @books`だけで表示されるよう修正しました。

2021-01-10 08:07 UTC, komagata requested changes

2021-01-10 08:07 UTC, komagata commented on .gitignore
> +.vscode
これはVSCodeを使っている人だけに必要な設定なので、自分のマシンに固有のignore設定に追記してプロジェクトのignoreには書かないほうがいいと思います〜

2021-01-21 05:27 UTC, merged